# Generated by Django 3.1.7 on 2021-03-13 16:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnumbers', '0005_auto_20210313_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partnumbers.partnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=30)),
                ('container_type', models.CharField(choices=[('sh', 'Ripiano'), ('shu', 'Scaffalatura'), ('dru', 'Cassettiera'), ('dr', 'Cassetto'), ('ar', 'Area'), ('bin', 'Contenitore')], default='sh', max_length=3, verbose_name='tipo di contenitore')),
                ('area', models.CharField(choices=[('pg', 'Area prelievo'), ('se', 'Area magazzino')], default='pg', max_length=3, verbose_name='destinazione')),
                ('items', models.ManyToManyField(through='warehouse.Item', to='partnumbers.Partnumber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.storage'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('partnumber', 'storage'), name='unique_partnumber_storage'),
        ),
    ]
