# Generated by Django 3.1.7 on 2021-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='container_type',
            field=models.CharField(choices=[('sh', 'Ripiano'), ('se', 'Sezione'), ('shu', 'Scaffalatura'), ('dru', 'Cassettiera'), ('dr', 'Cassetto'), ('ar', 'Area'), ('bin', 'Contenitore')], default='sh', max_length=3, verbose_name='tipo di contenitore'),
        ),
    ]
