# Generated by Django 3.1.7 on 2021-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210313_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='area',
        ),
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.CharField(choices=[('pg', 'Area prelievo'), ('se', 'Area magazzino')], default='pg', max_length=3, verbose_name='destinazione'),
        ),
    ]
