# Generated by Django 3.1.7 on 2021-03-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0005_auto_20210313_1703'),
        ('warehouse', '0003_auto_20210314_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='partnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partnumbers.partnumber', verbose_name='codice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.storage', verbose_name='magazzino'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(max_length=30, verbose_name='coordinata'),
        ),
    ]
