# Generated by Django 3.1.2 on 2020-10-08 18:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
        ('partnumbers', '0002_auto_20201008_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('picking_date', models.DateField(default=datetime.date.today)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspections.lot')),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partnumbers.partnumber')),
                ('picking_operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
