# Generated by Django 3.1.2 on 2020-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='picking_date',
            field=models.DateField(),
        ),
    ]
