version: "3.1"
volumes:
  gapapp_v1:
services:
  gapapp-v1:
    build:
      context: .
      dockerfile: Dockerfile
    image: gapapp-v1:latest
    container_name: gapapp-v1
    environment:
      - TZ=Europe/Rome
      - MODULE_NAME=gap.asgi
      - VARIABLE_NAME=application
      - PORT=8000
    volumes:
      - gapapp_v1:/app
    ports:
      - "8080:8000"
    restart: unless-stopped
