version: "3.4"

volumes:
  gapapp_v0.2:

services:
  gapapp-v0.2:
    build:
      context: .
      dockerfile: Dockerfile
    image: gapapp-v0.2:latest
    container_name: gapapp-v0.2
    user: gap:gap
    env_file:
      - ./gap/.env
    volumes:
      - gapapp_v0.2:/usr/src/app
    ports:
      - "8080:8000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true