version: "3.1"
volumes:
  gapapp_v0.2:
services:
  gapapp-v0.2:
    build:
      context: .
      dockerfile: Dockerfile
    #command: ["python", "./gap/manage.py", "runserver", "0.0.0.0:8000"]
    command: ["gunicorn", "--config", "./gap/gunicorn.conf.py", "gap.wsgi:application"]
    image: gapapp-v0.2:latest
    container_name: gapapp-v0.2
    env_file:
      - ./gap/.env
    volumes:
      - gapapp_v0.2:/usr/src/app
    ports:
      - "8080:8000"
    restart: unless-stopped
