#!/bin/bash
read -p "Build a new docker image? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker build -t gapimage ./
fi
docker volume create gapapp
docker run -d -p 8000:80 \
    --name gapapp \
    -v gapapp:/app \
    -e MODULE_NAME="gap.wsgi" \
    -e VARIABLE_NAME="application" \
    gapimage
