# Generated by Django 3.1.2 on 2020-11-14 17:25

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnumbers', '0004_auto_20201011_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(core.mixins.ValuesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('coc', models.CharField(db_index=True, max_length=60, verbose_name='nr COC')),
                ('orderdate', models.DateField(db_index=True, verbose_name='data ordine')),
                ('shipdate', models.DateField(db_index=True, verbose_name='data di consegna')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.company', verbose_name='cliente')),
            ],
            options={
                'ordering': ('orderdate',),
                'get_latest_by': 'orderdate',
            },
            bases=(core.mixins.ValuesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('planned', 'In programma'), ('released', 'In produzione'), ('closed', 'Evaso'), ('deleted', 'Annullato')], default='planned', max_length=12)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.IntegerField(verbose_name='pz ordinati')),
                ('coc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.order', verbose_name='COC')),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partnumbers.partnumber', verbose_name='Prodotto finito')),
            ],
            options={
                'verbose_name': 'prodotto finito',
                'verbose_name_plural': 'prodotto finito ordinato',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.Orderitem', to='partnumbers.Partnumber'),
        ),
    ]
