# Generated by Django 3.1.2 on 2020-11-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0004_auto_20201011_1424'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'finished good', 'verbose_name_plural': 'finished goods ordered'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(db_index=True, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipdate',
            field=models.DateField(db_index=True, verbose_name='shipment date'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='partnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partnumbers.partnumber', verbose_name='Finished Good'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='pcs ordered'),
        ),
    ]
