# Generated by Django 3.1.2 on 2020-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
