# Generated by Django 3.1.2 on 2020-10-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0002_auto_20201008_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='db_nr',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='pmu',
            field=models.FloatField(blank=True),
        ),
    ]
