# Generated by Django 3.1.7 on 2021-03-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0004_auto_20201011_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='partnumber',
            options={'ordering': ('sku',)},
        ),
    ]
