# Generated by Django 3.1.2 on 2020-10-08 18:57

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('lot_number', models.IntegerField()),
                ('lot_date', models.DateField(default=datetime.date.today)),
                ('subcontractor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('lot_number', 'lot_date', 'subcontractor'), name='unique_lot'),
        ),
    ]
