# Generated by Django 3.1.2 on 2020-10-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnumbers', '0002_auto_20201008_2057'),
        ('pickings', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='partnumbers',
            field=models.ManyToManyField(through='pickings.Picking', to='partnumbers.Partnumber'),
        ),
    ]
