# Generated by Django 3.1.2 on 2020-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_lot_partnumbers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lot',
            name='unique_lot',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='subcontractor',
        ),
        migrations.AddField(
            model_name='lot',
            name='supplier_type',
            field=models.CharField(choices=[('', 'Fornitore'), ('tz', 'TZ'), ('sclpun', 'SCL/pun'), ('int_pr', 'Produzione interna'), ('t', 'T'), ('r', 'R')], default='', max_length=6),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('lot_number', 'lot_date', 'supplier_type'), name='unique_lot'),
        ),
    ]
