# Generated by Django 3.1.2 on 2020-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_auto_20201023_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='supplier_type',
            field=models.CharField(choices=[('fn', ''), ('tz', 'TZ'), ('sclpun', 'SCL/pun'), ('int_pr', 'Produzione interna'), ('t', 'T'), ('r', 'R')], default='fn', max_length=6),
        ),
    ]
