# Generated by Django 3.1.2 on 2020-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_auto_20201023_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-lot_date', 'lot_number']},
        ),
        migrations.AlterField(
            model_name='lot',
            name='supplier_type',
            field=models.CharField(choices=[('fn', ''), ('tz', 'TZ'), ('sclpun', 'SCL/pun'), ('int_pr', 'Produzione interna'), ('t', 'T'), ('r', 'R'), ('QPS', 'QPS')], default='fn', max_length=6),
        ),
    ]
