# Generated by Django 3.1.7 on 2021-03-13 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20201029_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-lot_date', 'lot_number'], 'verbose_name': 'lotto'},
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_date',
            field=models.DateField(default=datetime.date.today, verbose_name='data di consegna'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.IntegerField(verbose_name='nr. lotto'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='supplier_type',
            field=models.CharField(choices=[('fn', ''), ('tz', 'TZ'), ('sclpun', 'SCL/pun'), ('int_pr', 'Produzione interna'), ('t', 'T'), ('r', 'R'), ('QPS', 'QPS')], default='fn', max_length=6, verbose_name='tipo di fornitura'),
        ),
    ]
